on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development
      - 'feature/**'
      - 'bugfix/**'
      - 'task/**'

permissions:
  pull-requests: write
  contents: write

jobs:
  run-tests:
    name: Run Unit Tests & Generate Coverage Report
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Grant execute permission to Gradle
        run: chmod +x ./gradlew

      - name: Run unit tests
        run: ./gradlew testDebugUnitTest

      - name: Generate coverage report
        run: ./gradlew jacocoTestReport

      - name: Check coverage threshold
        id: coverage
        run: |
          REPORT="${{ github.workspace }}/app/build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml"
          
          if [ ! -f "$REPORT" ]; then
            echo "❌ Report not found: $REPORT"
            exit 1
          fi
          
          MISSED=$(grep -oP '<counter type="LINE" missed="\K[0-9]+' "$REPORT" | tail -1)
          COVERED=$(grep -oP '<counter type="LINE" covered="\K[0-9]+' "$REPORT" | tail -1)
          
          MISSED=${MISSED:-0}
          COVERED=${COVERED:-0}
          TOTAL=$(( MISSED + COVERED ))
          
          if [ "$TOTAL" -eq 0 ]; then
            PERCENT=0
          else
            PERCENT=$(( 100 * COVERED / TOTAL ))
          fi
          
          echo "percent=$PERCENT" >> $GITHUB_OUTPUT
          
          if [ "$PERCENT" -lt 80 ]; then
            echo "❌ Test coverage is below 80% ($PERCENT%)"
            exit 1
          else
            echo "✅ Test coverage is sufficient ($PERCENT%)"
          fi

  analyze-pr:
    name: Analyze PR Code Coverage
    needs: run-tests
    if: github.event_name == 'pull_request' && always()
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download coverage reports
        uses: actions/download-artifact@v4
        continue-on-error: true
        with:
          name: jacoco-coverage-report
          path: build/reports/jacoco/

      - name: Add coverage results to PR
        id: jacoco-pr-comment
        uses: madrapps/jacoco-report@v1.7.1
        with:
          paths: ${{ github.workspace }}/build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 80
          min-coverage-changed-files: 80
          update-comment: true
          title: Code Coverage Summary
          pass-emoji: '✅'
          fail-emoji: '❌'