name: run tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
      - 'feature/**'
      - 'bugfix/**'
      - 'task/**'

permissions:
  pull-requests: write
  contents: write

jobs:
  run-tests:
    name: Execute Tests & Check Coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run unit tests with coverage
        run: |
          ./gradlew testDebugUnitTest jacocoTestReport jacocoTestCoverageVerification

      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: jacoco-coverage-report
          path: app/build/reports/jacoco/
          retention-days: 1

      - name: Test Summary
        uses: test-summary/action@v2
        with:
          paths: "**/build/test-results/**/*.xml"
        if: always()

  analyze-pr:
    name: Analyze PR Coverage
    needs: run-tests
    if: ${{ github.event_name == 'pull_request' && (always() || failure()) }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download coverage reports
        uses: actions/download-artifact@v4
        with:
          name: jacoco-coverage-report
          path: app/build/reports/jacoco/

      - name: Add coverage results to PR
        id: jacoco-pr-comment
        uses: madrapps/jacoco-report@v1.7.1
        with:
          paths: ${{ github.workspace }}/app/build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 80
          min-coverage-changed-files: 80
          update-comment: true
          title: 'Android Test Coverage'
          pass-emoji: '✅'
          fail-emoji: '❌'
          fail-on-coverage-decrease: false