name: run tests

on:
  pull_request:
    branches:
      - main
      - develop
      - 'feature/**'
      - 'task/**'
      - 'bugfix/**'
      - 'hotfix/**'

jobs:
  run-tests:
    name: Excecute tests & Generate coverage report
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Install xmllint (to read coverage XML)
        run: sudo apt-get install -y libxml2-utils

      - name: Run tests
        run: ./gradlew test

      - name: Generate JaCoCo report
        run: ./gradlew jacocoTestReport

      - name: Check minimum code coverage (80%)
        run: |
          echo "Checking JaCoCo line coverage..."
          FILE="app/build/reports/jacoco/test/jacocoTestReport.xml"
          
          if [ ! -f "$FILE" ]; then
            echo "Coverage report not found!"
            exit 1
          fi
          
          COVERED=$(xmllint --xpath "string(//report/counter[@type='LINE']/@covered)" $FILE)
          MISSED=$(xmllint --xpath "string(//report/counter[@type='LINE']/@missed)" $FILE)
          TOTAL=$((COVERED + MISSED))
          
          if [ "$TOTAL" -eq 0 ]; then
            echo "No lines found in coverage report!"
            exit 1
          fi
          
          PERCENT=$((100 * COVERED / TOTAL))
          echo "Line Coverage: $PERCENT%"
          
          if [ "$PERCENT" -lt 80 ]; then
            echo "❌ Code coverage is below 80%."
            exit 1
          else
            echo "✅ Code coverage is above threshold."
          fi
